#!/bin/bash

cmd_kubectl=${cmd_kubectl-kubectl}

# Get all namespaces
namespaces=$($cmd_kubectl get namespaces | awk '{print $1}' | tail -n +2) 

# Use fzf to select a namespace
selected_namespace=$(echo "$namespaces" | fzf --prompt="Select a namespace: ")

if [ -z "$selected_namespace" ]; then
  echo "No namespace selected."
  exit 1
fi

# Get all ConfigMaps in the selected namespace
config_maps=$($cmd_kubectl get configmaps -n "$selected_namespace" -o name | cut -d '/' -f2)

# Use fzf to select a ConfigMap
selected_config_map=$(echo "$config_maps" | fzf --prompt="Select a ConfigMap: ")

if [ -z "$selected_config_map" ]; then
  echo "No ConfigMap selected."
  exit 1
fi

# Delete the selected ConfigMap
$cmd_kubectl delete configmap "$selected_config_map" -n "$selected_namespace"

echo "ConfigMap '$selected_config_map' deleted from namespace '$selected_namespace'."

