#!/bin/bash

cmd_kubectl=${cmd_kubectl-kubectl}

# Get all namespaces
namespaces=$($cmd_kubectl get namespaces -o name | cut -d '/' -f2)

# Use fzf to select a namespace
selected_namespace=$(echo "$namespaces" | fzf --prompt="Select a namespace: ")

if [ -z "$selected_namespace" ]; then
  echo "No namespace selected."
  exit 1
fi

# Get all deployments in the selected namespace
deployments=$($cmd_kubectl get deployments -n "$selected_namespace" -o name | cut -d '/' -f2)

# Use fzf to select a deployment
selected_deployment=$(echo "$deployments" | fzf --prompt="Select a deployment: ")

if [ -z "$selected_deployment" ]; then
  echo "No deployment selected."
  exit 1
fi

# Delete the selected deployment
$cmd_kubectl delete deployment "$selected_deployment" -n "$selected_namespace"

echo "Deployment '$selected_deployment' deleted from namespace '$selected_namespace'."

