#!/bin/bash

cmd_kubectl=${cmd_kubectl-kubectl}

# Get all namespaces
namespaces=$($cmd_kubectl get namespaces -o name | cut -d '/' -f2)

# Use fzf to select a namespace
selected_namespace=$(echo "$namespaces" | fzf --prompt="Select a namespace: ")

if [ -z "$selected_namespace" ]; then
  echo "No namespace selected."
  exit 1
fi

# Get all pods in the selected namespace
pods=$($cmd_kubectl get pods -n "$selected_namespace" -o name | cut -d '/' -f2)

# Use fzf to select a pod
selected_pod=$(echo "$pods" | fzf --prompt="Select a pod: ")

if [ -z "$selected_pod" ]; then
  echo "No pod selected."
  exit 1
fi

$cmd_kubectl logs "$selected_pod" -n "$selected_namespace" | less

