#!/bin/bash

# Get all namespaces
namespaces=$($cmd_kubectl get namespaces | awk '{print $1}' | tail -n +2) 

# Use fzf to select a namespace
selected_namespace=$(echo "$namespaces" | fzf --prompt="Select a namespace: ")

if [ -z "$selected_namespace" ]; then
  echo "No namespace selected."
  exit 1
fi

# Get all pods in the selected namespace
pods=$(microk8s kubectl get pods -n "$selected_namespace" -o name | cut -d '/' -f2)

# Use fzf to select a pod
selected_pod=$(echo "$pods" | fzf --prompt="Select a pod: ")

if [ -z "$selected_pod" ]; then
  echo "No pod selected."
  exit 1
fi

# Get all containers in the selected pod
containers=$(microk8s kubectl get pod "$selected_pod" -n "$selected_namespace" -o jsonpath='{.spec.containers[*].name}')

# Use fzf to select a container
selected_container=$(echo "$containers" | tr ' ' '\n' | fzf --prompt="Select a container: ")

if [ -z "$selected_container" ]; then
  echo "No container selected."
  exit 1
fi

# Execute the microk8s kubectl command with the selections
microk8s kubectl exec -it "$selected_pod" -c "$selected_container" --namespace="$selected_namespace" -- /bin/sh

