#!/bin/bash

set -euo pipefail

locales=('us' 'it' 'tr')

loc_file=$(realpath ~/.config/.kbdlayout)
index=0

if [ ! -e $loc_file ]
then
    echo $index > $loc_file
else
    typeset -i index=$(cat "$loc_file")
    index=$(((index + 1) % 3))
    echo $index >  $loc_file
fi

setxkbmap "${locales[$index]}"
