#!/usr/bin/env bash

# Enable touchpad tapping
xinput set-prop 'CUST0001:00 04F3:30AA Touchpad' 'libinput Tapping Enabled' 1

export SCRIPTPATH="$HOME/.config/leftwm/themes/current" #"$( cd "$(dirname "$0")" ; pwd -P )"

#if path to liblinkt is not not exported do so:
if [ -z "$LD_LIBRARY_PATH" ]; then
  export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
fi

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# start eww daemon
# eww daemon &

# Boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  picom --experimental-backends --config $SCRIPTPATH/picom.conf &> /dev/null &
fi

# Set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

# Set background
if [ -x "$(command -v feh)" ]; then
  #feh --bg-scale $SCRIPTPATH/background.jpg
  $HOME/.config/leftwm/themes/current/feh.sh
fi

#open eww 'bar' windows
#this is a bit of an uggly hack, a more elegant way will hopefully be possible with a future `eww` version
# sleep 1
# index=0
# sizes=( $(leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' ) )
# for size in "${sizes[@]}"
# do
#     eww open bar$index
#   let index=index+1
# done
# eww open bar0

# index=0
# monitors="$(polybar -m | sed s/:.*//)"
# leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
# do
#   let indextemp=index+1
#   monitor=$(sed "$indextemp!d" <<<"$monitors")
#   barname="mainbar$index"
#   monitor=$monitor offset=$x width=$width polybar -c $SCRIPTPATH/polybar.config $barname &> /dev/null &
#   let index=indextemp
# done
sleep 1
polybar -c $SCRIPTPATH/polybar/config.ini main

