#!/bin/zsh

alias SP="source $HOME/dotfiles/zsh/rc"
alias l='exa -al --color=always --group-directories-first --icons'

# Replace some more things with better alternatives
# alias cat='bat --style header --style snip --style changes --style header'
alias bat="bat --theme OneHalfDark "

# Get the error messages from journalctl
alias jctl="journalctl -p 3 -xb"

# Recent installed packages
alias rip="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -200 | nl"

# alias vim='NVIM_MINIMAL=1 command nvim'
alias e='nvim'
export EDITOR='nvim'
# export EDITOR="/usr/bin/nvim"

# export BROWSER=firedragon
# export TERM=kitty
# export MAIL=thunderbird
# export QT_QPA_PLATFORMTHEME="qt5ct"
# export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

alias TMS="date -u +\"%Y-%m-%dT%H:%M:%S.%3N\""
alias CDOWN='curl -fsSLO'

alias wgkeygen="umask 077 && wg genkey >> private && wg pubkey < private >> public && umask 022"

if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

export PATH=$PATH:$HOME/dotfiles/scripts/scripts:$HOME/go/bin


if [ -d "$(pwd)/.dirme" ] ; then
    export PATH="$(pwd)/.dirme:$PATH"
fi


[[ -f ~/._private_profile ]] && source ~/._private_profile
